### ISSUE TITLE
Gnome extension

### ISSUE THREAD

**Issue by nater1983** [xynium/webfeed#3]
The Gnome extension website states this extension is at version 8 but the github states it is at version 6???

**Comment by xynium** [comment]
Hi,‌
I will correct that.
Tks
JP
De : "Nathaniel Russell"
A : "xynium/webfeed" ,"Subscribed"
Envoyé: samedi 24 Décembre 2022 02:42
Objet : [xynium/webfeed] Gnome extension (Issue #3)
 

 

The Gnome extension website states this extension is at version 8 but the github states it is at version 6???
